import { VirtualFsNode } from "../types";

export const filesystem: VirtualFsNode[] = [
	{
		name: "about",
		path: "/",
		type: "file",
		description: "overview + selected proof points",
		renderKey: "about",
	},
	{
		name: "now",
		path: "/",
		type: "file",
		description: "current focus and role target",
		renderKey: "now",
	},
	{
		name: "values",
		path: "/",
		type: "file",
		description: "working principles",
		renderKey: "values",
	},
	{
		name: "stats",
		path: "/",
		type: "file",
		description: "hard-number career anchors",
		renderKey: "stats",
	},
	{
		name: "source",
		path: "/",
		type: "file",
		description: "how public claims are maintained",
		renderKey: "source",
	},
	{
		name: "skills",
		path: "/",
		type: "file",
		description: "stack map and technical breadth",
		renderKey: "skills",
	},
	{
		name: "experience",
		path: "/",
		type: "file",
		description: "full work history",
		renderKey: "experience",
	},
	{
		name: "education",
		path: "/",
		type: "file",
		description: "formal education history",
		renderKey: "education",
	},
	{
		name: "socials",
		path: "/",
		type: "file",
		description: "public profiles and contact routes",
		renderKey: "socials",
	},
	{
		name: "themes",
		path: "/",
		type: "file",
		description: "available full-app palettes",
		renderKey: "themes",
	},
	{
		name: "projects",
		path: "/",
		type: "dir",
		description: "selected shipped work",
	},
	{
		name: "lab",
		path: "/",
		type: "dir",
		description: "side projects and curiosity",
	},
	{
		name: "meta",
		path: "/",
		type: "dir",
		description: "shell guidance and landing copy",
	},
	{
		name: "whichmodel",
		path: "/projects",
		type: "file",
		description: "AI model selection CLI",
		renderKey: "project:1",
	},
	{
		name: "souk-fighter",
		path: "/projects",
		type: "file",
		description: "browser fighting game",
		renderKey: "project:2",
	},
	{
		name: "radiometer",
		path: "/projects",
		type: "file",
		description: "six-figure enterprise healthcare build",
		renderKey: "project:3",
	},
	{
		name: "clicky-clicky",
		path: "/projects",
		type: "file",
		description: "computer-vision operations tooling",
		renderKey: "project:4",
	},
	{
		name: "overview",
		path: "/lab",
		type: "file",
		description: "public lab notes",
		renderKey: "lab",
	},
	{
		name: "42",
		path: "/lab",
		type: "file",
		description: "why 42 matters here",
		renderKey: "42",
		visibility: "hinted",
	},
	{
		name: "morocco",
		path: "/lab",
		type: "file",
		description: "Casablanca, Mohammedia, Khouribga",
		renderKey: "morocco",
		visibility: "hinted",
	},
	{
		name: "souk",
		path: "/lab",
		type: "file",
		description: "game-dev detour",
		renderKey: "souk",
		visibility: "hidden",
	},
	{
		name: "rescue",
		path: "/lab",
		type: "file",
		description: "broken-codebase mode",
		renderKey: "rescue",
		visibility: "hidden",
	},
	{
		name: "welcome",
		path: "/meta",
		type: "file",
		description: "landing copy",
		renderKey: "welcome",
	},
	{
		name: "help",
		path: "/meta",
		type: "file",
		description: "command manual index",
		renderKey: "help",
	},
];
