import { CommandCategory } from "../../types";

export const ROOT_PATH = "/";

export const KNOWN_TOOL_REPLIES: Record<string, string> = {
	vim: "No vim. `:q!` won't help — the cursor was never trapped.",
	vi: "vi not found. `cat about` works fine though.",
	nano: "nano not installed. Everything is readable via `cat`.",
	emacs: "M-x not-a-portfolio-editor",
	python: "Python is in `skills`, not in the shell runtime.",
	python3: "Python is in `skills`, not in the shell runtime.",
	node: "Node.js runs the server side. This is the client. Try `skills`.",
	bun: "Fast, but not here. The portfolio loads in milliseconds anyway.",
	npx: "npx create-portfolio — already done. Try `welcome`.",
	cargo: "Rust is not in the stack. Yet.",
	make: "No Makefile. No targets. Try `resume` for the fast path.",
	brew: "Homebrew is for packages, not portfolios.",
	apt: "apt: this is a browser, not Debian.",
	"apt-get": "apt-get: this is a browser, not Debian.",
	yum: "yum: this is a browser, not RHEL.",
	curl: "curl: no endpoints here. Try `socials` for links worth fetching.",
	wget: "wget: nothing to download. `projects` has the real links.",
	ping: "PING useit015@gmail.com: Request timeout — try `email` instead.",
	ssh: "You are already connected. oussama@terminal is the only session.",
	scp: "scp: nothing to copy. `resume` prints the fast-path summary.",
	exit: "exit: this session lives in the browser. Close the tab to leave.",
	quit: "quit: same answer as exit.",
	logout: "logout: there is no session to terminate.",
	reboot: "reboot: refresh the page if you must. The content will still be here.",
	shutdown: "shutdown -h now: not today.",
	top: "There are no processes. Just this terminal and your curiosity.",
	htop: "htop not installed. All commands run in O(1) portfolio time.",
	ps: "PID 1: /bin/portfolio — the only process that matters here.",
	kill: "kill: there are no processes to terminate.",
	touch: "touch: the portfolio is already writable by the author.",
	rm: "rm: the filesystem is fictional. You can't break anything here.",
	mkdir: "mkdir: no new directories needed. Try `tree` to see what exists.",
	mv: "mv: files can't be moved. They were always in the right place.",
	cp: "cp: nothing to copy. `cat <topic>` is the read path.",
	less: "less is more. But `cat` is the right command here.",
	more: "more: try `cat` instead.",
	tail: "tail: try `now` to see what's current.",
	head: "head: try `resume` for the fast read.",
	find: "find / -name curiosity: found. It's what got you this far.",
	awk: "awk '{print \"use grep instead\"}'",
	sed: "sed 's/jargon/clarity/g' — already applied to this entire portfolio.",
	sort: "sort: run `history` and pipe your own session.",
	uniq: "uniq: every project here is original.",
	wc: "wc -l: the codebase is approximately 2000 lines. Try `grep` instead.",
	diff: "diff: no changes since last commit. `git status` confirms.",
	zip: "zip: nothing to compress. The build is already optimized.",
	tar: "tar: no archives. Everything is live and readable.",
	chmod: "chmod 755: the portfolio is already world-readable.",
	chown: "chown: owned by Oussama. Can't change that.",
	open: "open: you're already inside. Look around.",
	code: "code .: no IDE needed here. The terminal is enough.",
	"code.": "Opening VS Code is how this portfolio was built. But `projects` shows what shipped.",
	nvim: "nvim: no vim, no neovim. The cursor was never trapped.",
	tmux: "tmux: one terminal is enough when it's well-designed.",
	screen: "screen: single-session portfolio. No detach needed.",
	zsh: "zsh: /bin/portfolio is the only shell here.",
	bash: "bash: same answer as zsh.",
	fish: "fish: swim in the portfolio instead.",
	pbcopy: "pbcopy: clipboard access not available. `email` is the clipboard.",
	which: "which oussama: /home/oussama/portfolio",
	whereis: "whereis oussama: here, building things.",
};

export const CATEGORY_LABELS: Record<CommandCategory, string> = {
	profile: "Profile",
	work: "Work",
	shell: "Shell",
	navigation: "Navigation",
	play: "Side Quests",
};
