import { CommandDescriptor } from "../../types";

export const COMMAND_REGISTRY: CommandDescriptor[] = [
	{
		name: "welcome",
		description: "display the welcome section",
		category: "profile",
		visibility: "public",
		usage: "welcome",
		examples: ["welcome"],
	},
	{
		name: "help",
		description: "show public commands",
		category: "navigation",
		visibility: "public",
		usage: "help",
		examples: ["help"],
	},
	{
		name: "ls",
		description: "list files in the virtual portfolio shell",
		category: "navigation",
		visibility: "public",
		usage: "ls [path]",
		examples: ["ls", "ls projects"],
		aliases: ["dir"],
	},
	{
		name: "cd",
		description: "change virtual directory",
		category: "navigation",
		visibility: "public",
		usage: "cd <path>",
		examples: ["cd projects", "cd ..", "cd ~"],
	},
	{
		name: "cat",
		description: "print a file or section",
		category: "navigation",
		visibility: "public",
		usage: "cat <topic>",
		examples: ["cat about", "cat projects/whichmodel"],
	},
	{
		name: "tree",
		description: "show the public directory tree",
		category: "navigation",
		visibility: "public",
		usage: "tree",
		examples: ["tree"],
	},
	{
		name: "grep",
		description: "search across the portfolio content",
		category: "navigation",
		visibility: "public",
		usage: "grep <term>",
		examples: ["grep react", "grep zambia"],
	},
	{
		name: "man",
		description: "show command details and examples",
		category: "navigation",
		visibility: "public",
		usage: "man <command>",
		examples: ["man cd", "man grep"],
	},
	{
		name: "about",
		description: "overview of Oussama Nahiz",
		category: "profile",
		visibility: "public",
		usage: "about",
		examples: ["about", "cat about"],
		aliases: ["bio"],
	},
	{
		name: "now",
		description: "current focus and role target",
		category: "profile",
		visibility: "public",
		usage: "now",
		examples: ["now", "cat now"],
	},
	{
		name: "values",
		description: "working principles",
		category: "profile",
		visibility: "public",
		usage: "values",
		examples: ["values", "cat values"],
	},
	{
		name: "stats",
		description: "hard-number career anchors",
		category: "profile",
		visibility: "public",
		usage: "stats",
		examples: ["stats", "cat stats"],
	},
	{
		name: "skills",
		description: "stack map and technical breadth",
		category: "profile",
		visibility: "public",
		usage: "skills",
		examples: ["skills", "cat skills"],
		aliases: ["stack"],
	},
	{
		name: "education",
		description: "education history",
		category: "profile",
		visibility: "public",
		usage: "education",
		examples: ["education", "cat education"],
	},
	{
		name: "socials",
		description: "public profiles and contact routes",
		category: "profile",
		visibility: "public",
		usage: "socials [go <id>]",
		examples: ["socials", "socials go 1"],
		aliases: ["contact"],
	},
	{
		name: "experience",
		description: "full work history",
		category: "work",
		visibility: "public",
		usage: "experience",
		examples: ["experience", "cat experience"],
		aliases: ["exp"],
	},
	{
		name: "projects",
		description: "browse selected shipped projects",
		category: "work",
		visibility: "public",
		usage: "projects [go <id>]",
		examples: ["projects", "projects go 2"],
	},
	{
		name: "lab",
		description: "side projects and curiosity",
		category: "work",
		visibility: "public",
		usage: "lab",
		examples: ["lab", "cat lab/overview"],
		aliases: ["play"],
	},
	{
		name: "themes",
		description: "list or switch themes",
		category: "shell",
		visibility: "public",
		usage: "themes [set <name>]",
		examples: ["themes", "themes set espresso"],
	},
	{
		name: "history",
		description: "show command history",
		category: "shell",
		visibility: "public",
		usage: "history",
		examples: ["history"],
	},
	{
		name: "pwd",
		description: "print current virtual working directory",
		category: "shell",
		visibility: "public",
		usage: "pwd",
		examples: ["pwd"],
	},
	{
		name: "whoami",
		description: "show current user",
		category: "shell",
		visibility: "public",
		usage: "whoami",
		examples: ["whoami"],
	},
	{
		name: "echo",
		description: "print whatever you pass in",
		category: "shell",
		visibility: "public",
		usage: "echo <text>",
		examples: ["echo hello world"],
	},
	{
		name: "email",
		description: "open an email draft",
		category: "shell",
		visibility: "public",
		usage: "email",
		examples: ["email"],
	},
	{
		name: "gui",
		description: "open an external profile",
		category: "shell",
		visibility: "public",
		usage: "gui",
		examples: ["gui"],
	},
	{
		name: "clear",
		description: "clear terminal output",
		category: "shell",
		visibility: "public",
		usage: "clear",
		examples: ["clear"],
	},
	{
		name: "resume",
		description: "condensed one-page overview — fast path for recruiters",
		category: "profile",
		visibility: "public",
		usage: "resume",
		examples: ["resume", "cv"],
		aliases: ["cv"],
	},
	{
		name: "42",
		description: "why the 42 / 1337 thread matters",
		category: "play",
		visibility: "hinted",
		usage: "42",
		examples: ["42"],
	},
	{
		name: "morocco",
		description: "the Casablanca / Mohammedia / Khouribga thread",
		category: "play",
		visibility: "hinted",
		usage: "morocco",
		examples: ["morocco"],
	},
	{
		name: "sudo",
		description: "playful recruiter call to action",
		category: "play",
		visibility: "hinted",
		usage: "sudo hire-me",
		examples: ["sudo hire-me"],
	},
	{
		name: "souk",
		description: "game-dev detour",
		category: "play",
		visibility: "hidden",
		usage: "souk",
		examples: ["souk"],
	},
	{
		name: "rescue",
		description: "broken-codebase mode",
		category: "play",
		visibility: "hidden",
		usage: "rescue",
		examples: ["rescue"],
	},
	{
		name: "neofetch",
		description: "system info — portfolio edition",
		category: "play",
		visibility: "hidden",
		usage: "neofetch",
		examples: ["neofetch"],
	},
	{
		name: "uname",
		description: "print system name",
		category: "shell",
		visibility: "hidden",
		usage: "uname [-a]",
		examples: ["uname", "uname -a"],
	},
	{
		name: "matrix",
		description: "wake up",
		category: "play",
		visibility: "hidden",
		usage: "matrix",
		examples: ["matrix"],
	},
	{
		name: "coffee",
		description: "essential fuel",
		category: "play",
		visibility: "hidden",
		usage: "coffee",
		examples: ["coffee"],
	},
	{
		name: "fortune",
		description: "a quote worth keeping",
		category: "play",
		visibility: "hidden",
		usage: "fortune",
		examples: ["fortune"],
	},
	{
		name: "git",
		description: "version control easter egg",
		category: "play",
		visibility: "hidden",
		usage: "git [log|status|diff|blame|push]",
		examples: ["git log", "git log --oneline", "git status", "git blame"],
	},
	{
		name: "npm",
		description: "package manager easter egg",
		category: "play",
		visibility: "hidden",
		usage: "npm [install|run <script>]",
		examples: ["npm install", "npm run dev", "npm run build"],
	},
	{
		name: "docker",
		description: "container easter egg",
		category: "play",
		visibility: "hidden",
		usage: "docker [ps|run|build]",
		examples: ["docker ps", "docker run", "docker build"],
	},
];

const COMMAND_MAP = new Map<string, CommandDescriptor>();
for (const spec of COMMAND_REGISTRY) {
	COMMAND_MAP.set(spec.name, spec);
	for (const alias of spec.aliases ?? []) {
		COMMAND_MAP.set(alias, spec);
	}
}

export const getCommandSpec = (token: string) => COMMAND_MAP.get(token.toLowerCase());

export const getPublicCommands = () =>
	COMMAND_REGISTRY.filter((command) => command.visibility === "public");

export const getPublicCommandCount = () => getPublicCommands().length;
